# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"Y\n\tTaxRecord\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x15\n\rannual_income\x18\x02 \x01(\x01\x12\x10\n\x08tax_paid\x18\x03 \x01(\x01\x12\x15\n\rmonths_worked\x18\x04 \x01(\x05\"{\n\x0ePensionRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x12\n\nbirth_year\x18\x02 \x01(\x05\x12\x1e\n\x16target_retirement_year\x18\x03 \x01(\x05\x12 \n\x07history\x18\x04 \x03(\x0b\x32\x0f.calc.TaxRecord\"\x9e\x01\n\x0fPensionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12!\n\x19\x65stimated_monthly_pension\x18\x02 \x01(\x01\x12!\n\x19total_accumulated_capital\x18\x03 \x01(\x01\x12\x1d\n\x15\x63\x61lculation_breakdown\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t2N\n\x0b\x43\x61lcService\x12?\n\x10\x43\x61lculatePension\x12\x14.calc.PensionRequest\x1a\x15.calc.PensionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAXRECORD']._serialized_start=20
  _globals['_TAXRECORD']._serialized_end=109
  _globals['_PENSIONREQUEST']._serialized_start=111
  _globals['_PENSIONREQUEST']._serialized_end=234
  _globals['_PENSIONRESPONSE']._serialized_start=237
  _globals['_PENSIONRESPONSE']._serialized_end=395
  _globals['_CALCSERVICE']._serialized_start=397
  _globals['_CALCSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
