<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocr.proto

namespace Ocr;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Ocr;

/**
 * Формат відповіді
 *
 * Generated from protobuf message <code>ocr.HelloResponse</code>
 */
class HelloResponse extends Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $message
     *              }
     */
    public function __construct($data = null)
    {
        Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, true);
        $this->message = $var;

        return $this;
    }
}
