<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto

namespace Ocr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ocr.OcrRequest</code>
 */
class OcrRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes file_content = 1;</code>
     */
    protected $file_content = '';
    /**
     * Generated from protobuf field <code>string file_extension = 2;</code>
     */
    protected $file_extension = '';
    /**
     * Generated from protobuf field <code>string document_type = 3;</code>
     */
    protected $document_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file_content
     *     @type string $file_extension
     *     @type string $document_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes file_content = 1;</code>
     * @return string
     */
    public function getFileContent()
    {
        return $this->file_content;
    }

    /**
     * Generated from protobuf field <code>bytes file_content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFileContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->file_content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_extension = 2;</code>
     * @return string
     */
    public function getFileExtension()
    {
        return $this->file_extension;
    }

    /**
     * Generated from protobuf field <code>string file_extension = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileExtension($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_extension = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string document_type = 3;</code>
     * @return string
     */
    public function getDocumentType()
    {
        return $this->document_type;
    }

    /**
     * Generated from protobuf field <code>string document_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->document_type = $var;

        return $this;
    }

}

