<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocr.proto

namespace Ocr;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\MapField;
use Google\Protobuf\Internal\Message;
use GPBMetadata\Ocr;

/**
 * Generated from protobuf message <code>ocr.OcrResponse</code>
 */
class OcrResponse extends Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;

    /**
     * Generated from protobuf field <code>string raw_text = 2;</code>
     */
    protected $raw_text = '';

    /**
     * Generated from protobuf field <code>map<string, string> data = 3;</code>
     */
    private $data;

    /**
     * Generated from protobuf field <code>float confidence = 4;</code>
     */
    protected $confidence = 0.0;

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type bool $success
     * @type string $raw_text
     * @type array|\Google\Protobuf\Internal\MapField $data
     * @type float $confidence
     * @type string $error_message
     *              }
     */
    public function __construct($data = null)
    {
        Ocr::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     *
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string raw_text = 2;</code>
     *
     * @return string
     */
    public function getRawText()
    {
        return $this->raw_text;
    }

    /**
     * Generated from protobuf field <code>string raw_text = 2;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setRawText($var)
    {
        GPBUtil::checkString($var, true);
        $this->raw_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> data = 3;</code>
     *
     * @return MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>map<string, string> data = 3;</code>
     *
     * @param  array|MapField  $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, GPBType::STRING, GPBType::STRING);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float confidence = 4;</code>
     *
     * @return float
     */
    public function getConfidence()
    {
        return $this->confidence;
    }

    /**
     * Generated from protobuf field <code>float confidence = 4;</code>
     *
     * @param  float  $var
     * @return $this
     */
    public function setConfidence($var)
    {
        GPBUtil::checkFloat($var);
        $this->confidence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     *
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, true);
        $this->error_message = $var;

        return $this;
    }
}
