<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace GPBMetadata;

class Calc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ž

calc.protocalc"
HelloRequest
name (	" 
HelloResponse
message (	2B
CalcService3
SayHello.calc.HelloRequest.calc.HelloResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

