<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto

namespace GPBMetadata;

class Ocr
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
é
	ocr.protoocr"Q

OcrRequest
file_content (
file_extension (	
document_type (	"²
OcrResponse
success (
raw_text (	(
data (2.ocr.OcrResponse.DataEntry

confidence (
error_message (	+
	DataEntry
key (	
value (	:82G

OcrService9
RecognizeTaxDocument.ocr.OcrRequest.ocr.OcrResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

