<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr.proto

namespace GPBMetadata;

class Ocr
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
™
	ocr.protoocr"
HelloRequest
name (	" 
HelloResponse
message (	2?

OcrService1
SayHello.ocr.HelloRequest.ocr.HelloResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

