// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calc.proto
#ifndef GRPC_calc_2eproto__INCLUDED
#define GRPC_calc_2eproto__INCLUDED

#include "calc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace calc {

class CalcService final {
 public:
  static constexpr char const* service_full_name() {
    return "calc.CalcService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::calc::PensionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calc::PensionResponse>> AsyncCalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calc::PensionResponse>>(AsyncCalculatePensionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calc::PensionResponse>> PrepareAsyncCalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::calc::PensionResponse>>(PrepareAsyncCalculatePensionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::calc::PensionResponse>* AsyncCalculatePensionRaw(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::calc::PensionResponse>* PrepareAsyncCalculatePensionRaw(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::calc::PensionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>> AsyncCalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>>(AsyncCalculatePensionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>> PrepareAsyncCalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>>(PrepareAsyncCalculatePensionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response, std::function<void(::grpc::Status)>) override;
      void CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>* AsyncCalculatePensionRaw(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>* PrepareAsyncCalculatePensionRaw(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalculatePension_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalculatePension(::grpc::ServerContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalculatePension : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalculatePension() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalculatePension() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculatePension(::grpc::ServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculatePension(::grpc::ServerContext* context, ::calc::PensionRequest* request, ::grpc::ServerAsyncResponseWriter< ::calc::PensionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalculatePension<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CalculatePension : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalculatePension() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::calc::PensionRequest, ::calc::PensionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response) { return this->CalculatePension(context, request, response); }));}
    void SetMessageAllocatorFor_CalculatePension(
        ::grpc::MessageAllocator< ::calc::PensionRequest, ::calc::PensionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::calc::PensionRequest, ::calc::PensionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalculatePension() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculatePension(::grpc::ServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculatePension(
      ::grpc::CallbackServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CalculatePension<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalculatePension : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalculatePension() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalculatePension() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculatePension(::grpc::ServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalculatePension : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalculatePension() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalculatePension() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculatePension(::grpc::ServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculatePension(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalculatePension : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalculatePension() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalculatePension(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalculatePension() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculatePension(::grpc::ServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculatePension(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalculatePension : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalculatePension() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::calc::PensionRequest, ::calc::PensionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::calc::PensionRequest, ::calc::PensionResponse>* streamer) {
                       return this->StreamedCalculatePension(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalculatePension() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalculatePension(::grpc::ServerContext* /*context*/, const ::calc::PensionRequest* /*request*/, ::calc::PensionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculatePension(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::calc::PensionRequest,::calc::PensionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalculatePension<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalculatePension<Service > StreamedService;
};

}  // namespace calc


#endif  // GRPC_calc_2eproto__INCLUDED
