// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: calc.proto

#include "calc.pb.h"
#include "calc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace calc {

static const char* CalcService_method_names[] = {
  "/calc.CalcService/CalculatePension",
};

std::unique_ptr< CalcService::Stub> CalcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CalcService::Stub> stub(new CalcService::Stub(channel, options));
  return stub;
}

CalcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CalculatePension_(CalcService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CalcService::Stub::CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::calc::PensionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::calc::PensionRequest, ::calc::PensionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculatePension_, context, request, response);
}

void CalcService::Stub::async::CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::calc::PensionRequest, ::calc::PensionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculatePension_, context, request, response, std::move(f));
}

void CalcService::Stub::async::CalculatePension(::grpc::ClientContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculatePension_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>* CalcService::Stub::PrepareAsyncCalculatePensionRaw(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::calc::PensionResponse, ::calc::PensionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculatePension_, context, request);
}

::grpc::ClientAsyncResponseReader< ::calc::PensionResponse>* CalcService::Stub::AsyncCalculatePensionRaw(::grpc::ClientContext* context, const ::calc::PensionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculatePensionRaw(context, request, cq);
  result->StartCall();
  return result;
}

CalcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CalcService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CalcService::Service, ::calc::PensionRequest, ::calc::PensionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CalcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::calc::PensionRequest* req,
             ::calc::PensionResponse* resp) {
               return service->CalculatePension(ctx, req, resp);
             }, this)));
}

CalcService::Service::~Service() {
}

::grpc::Status CalcService::Service::CalculatePension(::grpc::ServerContext* context, const ::calc::PensionRequest* request, ::calc::PensionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace calc

