// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

#include "calc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace calc {
PROTOBUF_CONSTEXPR TaxRecord::TaxRecord(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.annual_income_)*/0
  , /*decltype(_impl_.year_)*/0
  , /*decltype(_impl_.months_worked_)*/0
  , /*decltype(_impl_.tax_paid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TaxRecordDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaxRecordDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaxRecordDefaultTypeInternal() {}
  union {
    TaxRecord _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaxRecordDefaultTypeInternal _TaxRecord_default_instance_;
PROTOBUF_CONSTEXPR PensionRequest::PensionRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.history_)*/{}
  , /*decltype(_impl_.customer_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.birth_year_)*/0
  , /*decltype(_impl_.target_retirement_year_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PensionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PensionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PensionRequestDefaultTypeInternal() {}
  union {
    PensionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PensionRequestDefaultTypeInternal _PensionRequest_default_instance_;
PROTOBUF_CONSTEXPR PensionResponse::PensionResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.calculation_breakdown_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.estimated_monthly_pension_)*/0
  , /*decltype(_impl_.total_accumulated_capital_)*/0
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PensionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PensionResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PensionResponseDefaultTypeInternal() {}
  union {
    PensionResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PensionResponseDefaultTypeInternal _PensionResponse_default_instance_;
}  // namespace calc
static ::_pb::Metadata file_level_metadata_calc_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_calc_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_calc_2eproto = nullptr;

const uint32_t TableStruct_calc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::calc::TaxRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::calc::TaxRecord, _impl_.year_),
  PROTOBUF_FIELD_OFFSET(::calc::TaxRecord, _impl_.annual_income_),
  PROTOBUF_FIELD_OFFSET(::calc::TaxRecord, _impl_.tax_paid_),
  PROTOBUF_FIELD_OFFSET(::calc::TaxRecord, _impl_.months_worked_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::calc::PensionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::calc::PensionRequest, _impl_.customer_id_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionRequest, _impl_.birth_year_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionRequest, _impl_.target_retirement_year_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionRequest, _impl_.history_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::calc::PensionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::calc::PensionResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionResponse, _impl_.estimated_monthly_pension_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionResponse, _impl_.total_accumulated_capital_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionResponse, _impl_.calculation_breakdown_),
  PROTOBUF_FIELD_OFFSET(::calc::PensionResponse, _impl_.error_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::calc::TaxRecord)},
  { 10, -1, -1, sizeof(::calc::PensionRequest)},
  { 20, -1, -1, sizeof(::calc::PensionResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::calc::_TaxRecord_default_instance_._instance,
  &::calc::_PensionRequest_default_instance_._instance,
  &::calc::_PensionResponse_default_instance_._instance,
};

const char descriptor_table_protodef_calc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ncalc.proto\022\004calc\"Y\n\tTaxRecord\022\014\n\004year\030"
  "\001 \001(\005\022\025\n\rannual_income\030\002 \001(\001\022\020\n\010tax_paid"
  "\030\003 \001(\001\022\025\n\rmonths_worked\030\004 \001(\005\"{\n\016Pension"
  "Request\022\023\n\013customer_id\030\001 \001(\t\022\022\n\nbirth_ye"
  "ar\030\002 \001(\005\022\036\n\026target_retirement_year\030\003 \001(\005"
  "\022 \n\007history\030\004 \003(\0132\017.calc.TaxRecord\"\236\001\n\017P"
  "ensionResponse\022\017\n\007success\030\001 \001(\010\022!\n\031estim"
  "ated_monthly_pension\030\002 \001(\001\022!\n\031total_accu"
  "mulated_capital\030\003 \001(\001\022\035\n\025calculation_bre"
  "akdown\030\004 \001(\t\022\025\n\rerror_message\030\005 \001(\t2N\n\013C"
  "alcService\022\?\n\020CalculatePension\022\024.calc.Pe"
  "nsionRequest\032\025.calc.PensionResponseb\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_calc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_calc_2eproto = {
    false, false, 483, descriptor_table_protodef_calc_2eproto,
    "calc.proto",
    &descriptor_table_calc_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_calc_2eproto::offsets,
    file_level_metadata_calc_2eproto, file_level_enum_descriptors_calc_2eproto,
    file_level_service_descriptors_calc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_calc_2eproto_getter() {
  return &descriptor_table_calc_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_calc_2eproto(&descriptor_table_calc_2eproto);
namespace calc {

// ===================================================================

class TaxRecord::_Internal {
 public:
};

TaxRecord::TaxRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:calc.TaxRecord)
}
TaxRecord::TaxRecord(const TaxRecord& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TaxRecord* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.annual_income_){}
    , decltype(_impl_.year_){}
    , decltype(_impl_.months_worked_){}
    , decltype(_impl_.tax_paid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.annual_income_, &from._impl_.annual_income_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.tax_paid_) -
    reinterpret_cast<char*>(&_impl_.annual_income_)) + sizeof(_impl_.tax_paid_));
  // @@protoc_insertion_point(copy_constructor:calc.TaxRecord)
}

inline void TaxRecord::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.annual_income_){0}
    , decltype(_impl_.year_){0}
    , decltype(_impl_.months_worked_){0}
    , decltype(_impl_.tax_paid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TaxRecord::~TaxRecord() {
  // @@protoc_insertion_point(destructor:calc.TaxRecord)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TaxRecord::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TaxRecord::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TaxRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:calc.TaxRecord)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.annual_income_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.tax_paid_) -
      reinterpret_cast<char*>(&_impl_.annual_income_)) + sizeof(_impl_.tax_paid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TaxRecord::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 year = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.year_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double annual_income = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.annual_income_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double tax_paid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.tax_paid_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int32 months_worked = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.months_worked_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TaxRecord::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calc.TaxRecord)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 year = 1;
  if (this->_internal_year() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_year(), target);
  }

  // double annual_income = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_annual_income = this->_internal_annual_income();
  uint64_t raw_annual_income;
  memcpy(&raw_annual_income, &tmp_annual_income, sizeof(tmp_annual_income));
  if (raw_annual_income != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_annual_income(), target);
  }

  // double tax_paid = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tax_paid = this->_internal_tax_paid();
  uint64_t raw_tax_paid;
  memcpy(&raw_tax_paid, &tmp_tax_paid, sizeof(tmp_tax_paid));
  if (raw_tax_paid != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_tax_paid(), target);
  }

  // int32 months_worked = 4;
  if (this->_internal_months_worked() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_months_worked(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calc.TaxRecord)
  return target;
}

size_t TaxRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calc.TaxRecord)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double annual_income = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_annual_income = this->_internal_annual_income();
  uint64_t raw_annual_income;
  memcpy(&raw_annual_income, &tmp_annual_income, sizeof(tmp_annual_income));
  if (raw_annual_income != 0) {
    total_size += 1 + 8;
  }

  // int32 year = 1;
  if (this->_internal_year() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_year());
  }

  // int32 months_worked = 4;
  if (this->_internal_months_worked() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_months_worked());
  }

  // double tax_paid = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tax_paid = this->_internal_tax_paid();
  uint64_t raw_tax_paid;
  memcpy(&raw_tax_paid, &tmp_tax_paid, sizeof(tmp_tax_paid));
  if (raw_tax_paid != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TaxRecord::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TaxRecord::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TaxRecord::GetClassData() const { return &_class_data_; }


void TaxRecord::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TaxRecord*>(&to_msg);
  auto& from = static_cast<const TaxRecord&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calc.TaxRecord)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_annual_income = from._internal_annual_income();
  uint64_t raw_annual_income;
  memcpy(&raw_annual_income, &tmp_annual_income, sizeof(tmp_annual_income));
  if (raw_annual_income != 0) {
    _this->_internal_set_annual_income(from._internal_annual_income());
  }
  if (from._internal_year() != 0) {
    _this->_internal_set_year(from._internal_year());
  }
  if (from._internal_months_worked() != 0) {
    _this->_internal_set_months_worked(from._internal_months_worked());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_tax_paid = from._internal_tax_paid();
  uint64_t raw_tax_paid;
  memcpy(&raw_tax_paid, &tmp_tax_paid, sizeof(tmp_tax_paid));
  if (raw_tax_paid != 0) {
    _this->_internal_set_tax_paid(from._internal_tax_paid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TaxRecord::CopyFrom(const TaxRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calc.TaxRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TaxRecord::IsInitialized() const {
  return true;
}

void TaxRecord::InternalSwap(TaxRecord* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TaxRecord, _impl_.tax_paid_)
      + sizeof(TaxRecord::_impl_.tax_paid_)
      - PROTOBUF_FIELD_OFFSET(TaxRecord, _impl_.annual_income_)>(
          reinterpret_cast<char*>(&_impl_.annual_income_),
          reinterpret_cast<char*>(&other->_impl_.annual_income_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TaxRecord::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_calc_2eproto_getter, &descriptor_table_calc_2eproto_once,
      file_level_metadata_calc_2eproto[0]);
}

// ===================================================================

class PensionRequest::_Internal {
 public:
};

PensionRequest::PensionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:calc.PensionRequest)
}
PensionRequest::PensionRequest(const PensionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PensionRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.history_){from._impl_.history_}
    , decltype(_impl_.customer_id_){}
    , decltype(_impl_.birth_year_){}
    , decltype(_impl_.target_retirement_year_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.customer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.customer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_customer_id().empty()) {
    _this->_impl_.customer_id_.Set(from._internal_customer_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.birth_year_, &from._impl_.birth_year_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.target_retirement_year_) -
    reinterpret_cast<char*>(&_impl_.birth_year_)) + sizeof(_impl_.target_retirement_year_));
  // @@protoc_insertion_point(copy_constructor:calc.PensionRequest)
}

inline void PensionRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.history_){arena}
    , decltype(_impl_.customer_id_){}
    , decltype(_impl_.birth_year_){0}
    , decltype(_impl_.target_retirement_year_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.customer_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.customer_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PensionRequest::~PensionRequest() {
  // @@protoc_insertion_point(destructor:calc.PensionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PensionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.history_.~RepeatedPtrField();
  _impl_.customer_id_.Destroy();
}

void PensionRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PensionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calc.PensionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.history_.Clear();
  _impl_.customer_id_.ClearToEmpty();
  ::memset(&_impl_.birth_year_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.target_retirement_year_) -
      reinterpret_cast<char*>(&_impl_.birth_year_)) + sizeof(_impl_.target_retirement_year_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PensionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string customer_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_customer_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "calc.PensionRequest.customer_id"));
        } else
          goto handle_unusual;
        continue;
      // int32 birth_year = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.birth_year_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 target_retirement_year = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.target_retirement_year_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .calc.TaxRecord history = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_history(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PensionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calc.PensionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string customer_id = 1;
  if (!this->_internal_customer_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_customer_id().data(), static_cast<int>(this->_internal_customer_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "calc.PensionRequest.customer_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_customer_id(), target);
  }

  // int32 birth_year = 2;
  if (this->_internal_birth_year() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_birth_year(), target);
  }

  // int32 target_retirement_year = 3;
  if (this->_internal_target_retirement_year() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_target_retirement_year(), target);
  }

  // repeated .calc.TaxRecord history = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_history_size()); i < n; i++) {
    const auto& repfield = this->_internal_history(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calc.PensionRequest)
  return target;
}

size_t PensionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calc.PensionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .calc.TaxRecord history = 4;
  total_size += 1UL * this->_internal_history_size();
  for (const auto& msg : this->_impl_.history_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string customer_id = 1;
  if (!this->_internal_customer_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_customer_id());
  }

  // int32 birth_year = 2;
  if (this->_internal_birth_year() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_birth_year());
  }

  // int32 target_retirement_year = 3;
  if (this->_internal_target_retirement_year() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_target_retirement_year());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PensionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PensionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PensionRequest::GetClassData() const { return &_class_data_; }


void PensionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PensionRequest*>(&to_msg);
  auto& from = static_cast<const PensionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calc.PensionRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.history_.MergeFrom(from._impl_.history_);
  if (!from._internal_customer_id().empty()) {
    _this->_internal_set_customer_id(from._internal_customer_id());
  }
  if (from._internal_birth_year() != 0) {
    _this->_internal_set_birth_year(from._internal_birth_year());
  }
  if (from._internal_target_retirement_year() != 0) {
    _this->_internal_set_target_retirement_year(from._internal_target_retirement_year());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PensionRequest::CopyFrom(const PensionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calc.PensionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PensionRequest::IsInitialized() const {
  return true;
}

void PensionRequest::InternalSwap(PensionRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.history_.InternalSwap(&other->_impl_.history_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.customer_id_, lhs_arena,
      &other->_impl_.customer_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PensionRequest, _impl_.target_retirement_year_)
      + sizeof(PensionRequest::_impl_.target_retirement_year_)
      - PROTOBUF_FIELD_OFFSET(PensionRequest, _impl_.birth_year_)>(
          reinterpret_cast<char*>(&_impl_.birth_year_),
          reinterpret_cast<char*>(&other->_impl_.birth_year_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PensionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_calc_2eproto_getter, &descriptor_table_calc_2eproto_once,
      file_level_metadata_calc_2eproto[1]);
}

// ===================================================================

class PensionResponse::_Internal {
 public:
};

PensionResponse::PensionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:calc.PensionResponse)
}
PensionResponse::PensionResponse(const PensionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PensionResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.calculation_breakdown_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.estimated_monthly_pension_){}
    , decltype(_impl_.total_accumulated_capital_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.calculation_breakdown_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.calculation_breakdown_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_calculation_breakdown().empty()) {
    _this->_impl_.calculation_breakdown_.Set(from._internal_calculation_breakdown(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.estimated_monthly_pension_, &from._impl_.estimated_monthly_pension_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.success_) -
    reinterpret_cast<char*>(&_impl_.estimated_monthly_pension_)) + sizeof(_impl_.success_));
  // @@protoc_insertion_point(copy_constructor:calc.PensionResponse)
}

inline void PensionResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.calculation_breakdown_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.estimated_monthly_pension_){0}
    , decltype(_impl_.total_accumulated_capital_){0}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.calculation_breakdown_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.calculation_breakdown_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PensionResponse::~PensionResponse() {
  // @@protoc_insertion_point(destructor:calc.PensionResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PensionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.calculation_breakdown_.Destroy();
  _impl_.error_message_.Destroy();
}

void PensionResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PensionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calc.PensionResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.calculation_breakdown_.ClearToEmpty();
  _impl_.error_message_.ClearToEmpty();
  ::memset(&_impl_.estimated_monthly_pension_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.estimated_monthly_pension_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PensionResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double estimated_monthly_pension = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.estimated_monthly_pension_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double total_accumulated_capital = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.total_accumulated_capital_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string calculation_breakdown = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_calculation_breakdown();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "calc.PensionResponse.calculation_breakdown"));
        } else
          goto handle_unusual;
        continue;
      // string error_message = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "calc.PensionResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PensionResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calc.PensionResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // double estimated_monthly_pension = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_estimated_monthly_pension = this->_internal_estimated_monthly_pension();
  uint64_t raw_estimated_monthly_pension;
  memcpy(&raw_estimated_monthly_pension, &tmp_estimated_monthly_pension, sizeof(tmp_estimated_monthly_pension));
  if (raw_estimated_monthly_pension != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_estimated_monthly_pension(), target);
  }

  // double total_accumulated_capital = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_total_accumulated_capital = this->_internal_total_accumulated_capital();
  uint64_t raw_total_accumulated_capital;
  memcpy(&raw_total_accumulated_capital, &tmp_total_accumulated_capital, sizeof(tmp_total_accumulated_capital));
  if (raw_total_accumulated_capital != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_total_accumulated_capital(), target);
  }

  // string calculation_breakdown = 4;
  if (!this->_internal_calculation_breakdown().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_calculation_breakdown().data(), static_cast<int>(this->_internal_calculation_breakdown().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "calc.PensionResponse.calculation_breakdown");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_calculation_breakdown(), target);
  }

  // string error_message = 5;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "calc.PensionResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calc.PensionResponse)
  return target;
}

size_t PensionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calc.PensionResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string calculation_breakdown = 4;
  if (!this->_internal_calculation_breakdown().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_calculation_breakdown());
  }

  // string error_message = 5;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // double estimated_monthly_pension = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_estimated_monthly_pension = this->_internal_estimated_monthly_pension();
  uint64_t raw_estimated_monthly_pension;
  memcpy(&raw_estimated_monthly_pension, &tmp_estimated_monthly_pension, sizeof(tmp_estimated_monthly_pension));
  if (raw_estimated_monthly_pension != 0) {
    total_size += 1 + 8;
  }

  // double total_accumulated_capital = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_total_accumulated_capital = this->_internal_total_accumulated_capital();
  uint64_t raw_total_accumulated_capital;
  memcpy(&raw_total_accumulated_capital, &tmp_total_accumulated_capital, sizeof(tmp_total_accumulated_capital));
  if (raw_total_accumulated_capital != 0) {
    total_size += 1 + 8;
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PensionResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PensionResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PensionResponse::GetClassData() const { return &_class_data_; }


void PensionResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PensionResponse*>(&to_msg);
  auto& from = static_cast<const PensionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calc.PensionResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_calculation_breakdown().empty()) {
    _this->_internal_set_calculation_breakdown(from._internal_calculation_breakdown());
  }
  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_estimated_monthly_pension = from._internal_estimated_monthly_pension();
  uint64_t raw_estimated_monthly_pension;
  memcpy(&raw_estimated_monthly_pension, &tmp_estimated_monthly_pension, sizeof(tmp_estimated_monthly_pension));
  if (raw_estimated_monthly_pension != 0) {
    _this->_internal_set_estimated_monthly_pension(from._internal_estimated_monthly_pension());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_total_accumulated_capital = from._internal_total_accumulated_capital();
  uint64_t raw_total_accumulated_capital;
  memcpy(&raw_total_accumulated_capital, &tmp_total_accumulated_capital, sizeof(tmp_total_accumulated_capital));
  if (raw_total_accumulated_capital != 0) {
    _this->_internal_set_total_accumulated_capital(from._internal_total_accumulated_capital());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PensionResponse::CopyFrom(const PensionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calc.PensionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PensionResponse::IsInitialized() const {
  return true;
}

void PensionResponse::InternalSwap(PensionResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.calculation_breakdown_, lhs_arena,
      &other->_impl_.calculation_breakdown_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PensionResponse, _impl_.success_)
      + sizeof(PensionResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(PensionResponse, _impl_.estimated_monthly_pension_)>(
          reinterpret_cast<char*>(&_impl_.estimated_monthly_pension_),
          reinterpret_cast<char*>(&other->_impl_.estimated_monthly_pension_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PensionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_calc_2eproto_getter, &descriptor_table_calc_2eproto_once,
      file_level_metadata_calc_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace calc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::calc::TaxRecord*
Arena::CreateMaybeMessage< ::calc::TaxRecord >(Arena* arena) {
  return Arena::CreateMessageInternal< ::calc::TaxRecord >(arena);
}
template<> PROTOBUF_NOINLINE ::calc::PensionRequest*
Arena::CreateMaybeMessage< ::calc::PensionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::calc::PensionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::calc::PensionResponse*
Arena::CreateMaybeMessage< ::calc::PensionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::calc::PensionResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
