// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_calc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_calc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_calc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_calc_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_calc_2eproto;
namespace calc {
class PensionRequest;
struct PensionRequestDefaultTypeInternal;
extern PensionRequestDefaultTypeInternal _PensionRequest_default_instance_;
class PensionResponse;
struct PensionResponseDefaultTypeInternal;
extern PensionResponseDefaultTypeInternal _PensionResponse_default_instance_;
class TaxRecord;
struct TaxRecordDefaultTypeInternal;
extern TaxRecordDefaultTypeInternal _TaxRecord_default_instance_;
}  // namespace calc
PROTOBUF_NAMESPACE_OPEN
template<> ::calc::PensionRequest* Arena::CreateMaybeMessage<::calc::PensionRequest>(Arena*);
template<> ::calc::PensionResponse* Arena::CreateMaybeMessage<::calc::PensionResponse>(Arena*);
template<> ::calc::TaxRecord* Arena::CreateMaybeMessage<::calc::TaxRecord>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace calc {

// ===================================================================

class TaxRecord final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:calc.TaxRecord) */ {
 public:
  inline TaxRecord() : TaxRecord(nullptr) {}
  ~TaxRecord() override;
  explicit PROTOBUF_CONSTEXPR TaxRecord(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TaxRecord(const TaxRecord& from);
  TaxRecord(TaxRecord&& from) noexcept
    : TaxRecord() {
    *this = ::std::move(from);
  }

  inline TaxRecord& operator=(const TaxRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaxRecord& operator=(TaxRecord&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaxRecord& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaxRecord* internal_default_instance() {
    return reinterpret_cast<const TaxRecord*>(
               &_TaxRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TaxRecord& a, TaxRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(TaxRecord* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaxRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaxRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TaxRecord>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TaxRecord& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TaxRecord& from) {
    TaxRecord::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaxRecord* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "calc.TaxRecord";
  }
  protected:
  explicit TaxRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAnnualIncomeFieldNumber = 2,
    kYearFieldNumber = 1,
    kMonthsWorkedFieldNumber = 4,
    kTaxPaidFieldNumber = 3,
  };
  // double annual_income = 2;
  void clear_annual_income();
  double annual_income() const;
  void set_annual_income(double value);
  private:
  double _internal_annual_income() const;
  void _internal_set_annual_income(double value);
  public:

  // int32 year = 1;
  void clear_year();
  int32_t year() const;
  void set_year(int32_t value);
  private:
  int32_t _internal_year() const;
  void _internal_set_year(int32_t value);
  public:

  // int32 months_worked = 4;
  void clear_months_worked();
  int32_t months_worked() const;
  void set_months_worked(int32_t value);
  private:
  int32_t _internal_months_worked() const;
  void _internal_set_months_worked(int32_t value);
  public:

  // double tax_paid = 3;
  void clear_tax_paid();
  double tax_paid() const;
  void set_tax_paid(double value);
  private:
  double _internal_tax_paid() const;
  void _internal_set_tax_paid(double value);
  public:

  // @@protoc_insertion_point(class_scope:calc.TaxRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double annual_income_;
    int32_t year_;
    int32_t months_worked_;
    double tax_paid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calc_2eproto;
};
// -------------------------------------------------------------------

class PensionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:calc.PensionRequest) */ {
 public:
  inline PensionRequest() : PensionRequest(nullptr) {}
  ~PensionRequest() override;
  explicit PROTOBUF_CONSTEXPR PensionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PensionRequest(const PensionRequest& from);
  PensionRequest(PensionRequest&& from) noexcept
    : PensionRequest() {
    *this = ::std::move(from);
  }

  inline PensionRequest& operator=(const PensionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PensionRequest& operator=(PensionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PensionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PensionRequest* internal_default_instance() {
    return reinterpret_cast<const PensionRequest*>(
               &_PensionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PensionRequest& a, PensionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PensionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PensionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PensionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PensionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PensionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PensionRequest& from) {
    PensionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PensionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "calc.PensionRequest";
  }
  protected:
  explicit PensionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHistoryFieldNumber = 4,
    kCustomerIdFieldNumber = 1,
    kBirthYearFieldNumber = 2,
    kTargetRetirementYearFieldNumber = 3,
  };
  // repeated .calc.TaxRecord history = 4;
  int history_size() const;
  private:
  int _internal_history_size() const;
  public:
  void clear_history();
  ::calc::TaxRecord* mutable_history(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::calc::TaxRecord >*
      mutable_history();
  private:
  const ::calc::TaxRecord& _internal_history(int index) const;
  ::calc::TaxRecord* _internal_add_history();
  public:
  const ::calc::TaxRecord& history(int index) const;
  ::calc::TaxRecord* add_history();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::calc::TaxRecord >&
      history() const;

  // string customer_id = 1;
  void clear_customer_id();
  const std::string& customer_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_customer_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_customer_id();
  PROTOBUF_NODISCARD std::string* release_customer_id();
  void set_allocated_customer_id(std::string* customer_id);
  private:
  const std::string& _internal_customer_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_customer_id(const std::string& value);
  std::string* _internal_mutable_customer_id();
  public:

  // int32 birth_year = 2;
  void clear_birth_year();
  int32_t birth_year() const;
  void set_birth_year(int32_t value);
  private:
  int32_t _internal_birth_year() const;
  void _internal_set_birth_year(int32_t value);
  public:

  // int32 target_retirement_year = 3;
  void clear_target_retirement_year();
  int32_t target_retirement_year() const;
  void set_target_retirement_year(int32_t value);
  private:
  int32_t _internal_target_retirement_year() const;
  void _internal_set_target_retirement_year(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:calc.PensionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::calc::TaxRecord > history_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr customer_id_;
    int32_t birth_year_;
    int32_t target_retirement_year_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calc_2eproto;
};
// -------------------------------------------------------------------

class PensionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:calc.PensionResponse) */ {
 public:
  inline PensionResponse() : PensionResponse(nullptr) {}
  ~PensionResponse() override;
  explicit PROTOBUF_CONSTEXPR PensionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PensionResponse(const PensionResponse& from);
  PensionResponse(PensionResponse&& from) noexcept
    : PensionResponse() {
    *this = ::std::move(from);
  }

  inline PensionResponse& operator=(const PensionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PensionResponse& operator=(PensionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PensionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PensionResponse* internal_default_instance() {
    return reinterpret_cast<const PensionResponse*>(
               &_PensionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PensionResponse& a, PensionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PensionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PensionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PensionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PensionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PensionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PensionResponse& from) {
    PensionResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PensionResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "calc.PensionResponse";
  }
  protected:
  explicit PensionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCalculationBreakdownFieldNumber = 4,
    kErrorMessageFieldNumber = 5,
    kEstimatedMonthlyPensionFieldNumber = 2,
    kTotalAccumulatedCapitalFieldNumber = 3,
    kSuccessFieldNumber = 1,
  };
  // string calculation_breakdown = 4;
  void clear_calculation_breakdown();
  const std::string& calculation_breakdown() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_calculation_breakdown(ArgT0&& arg0, ArgT... args);
  std::string* mutable_calculation_breakdown();
  PROTOBUF_NODISCARD std::string* release_calculation_breakdown();
  void set_allocated_calculation_breakdown(std::string* calculation_breakdown);
  private:
  const std::string& _internal_calculation_breakdown() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_calculation_breakdown(const std::string& value);
  std::string* _internal_mutable_calculation_breakdown();
  public:

  // string error_message = 5;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // double estimated_monthly_pension = 2;
  void clear_estimated_monthly_pension();
  double estimated_monthly_pension() const;
  void set_estimated_monthly_pension(double value);
  private:
  double _internal_estimated_monthly_pension() const;
  void _internal_set_estimated_monthly_pension(double value);
  public:

  // double total_accumulated_capital = 3;
  void clear_total_accumulated_capital();
  double total_accumulated_capital() const;
  void set_total_accumulated_capital(double value);
  private:
  double _internal_total_accumulated_capital() const;
  void _internal_set_total_accumulated_capital(double value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:calc.PensionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr calculation_breakdown_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    double estimated_monthly_pension_;
    double total_accumulated_capital_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_calc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TaxRecord

// int32 year = 1;
inline void TaxRecord::clear_year() {
  _impl_.year_ = 0;
}
inline int32_t TaxRecord::_internal_year() const {
  return _impl_.year_;
}
inline int32_t TaxRecord::year() const {
  // @@protoc_insertion_point(field_get:calc.TaxRecord.year)
  return _internal_year();
}
inline void TaxRecord::_internal_set_year(int32_t value) {
  
  _impl_.year_ = value;
}
inline void TaxRecord::set_year(int32_t value) {
  _internal_set_year(value);
  // @@protoc_insertion_point(field_set:calc.TaxRecord.year)
}

// double annual_income = 2;
inline void TaxRecord::clear_annual_income() {
  _impl_.annual_income_ = 0;
}
inline double TaxRecord::_internal_annual_income() const {
  return _impl_.annual_income_;
}
inline double TaxRecord::annual_income() const {
  // @@protoc_insertion_point(field_get:calc.TaxRecord.annual_income)
  return _internal_annual_income();
}
inline void TaxRecord::_internal_set_annual_income(double value) {
  
  _impl_.annual_income_ = value;
}
inline void TaxRecord::set_annual_income(double value) {
  _internal_set_annual_income(value);
  // @@protoc_insertion_point(field_set:calc.TaxRecord.annual_income)
}

// double tax_paid = 3;
inline void TaxRecord::clear_tax_paid() {
  _impl_.tax_paid_ = 0;
}
inline double TaxRecord::_internal_tax_paid() const {
  return _impl_.tax_paid_;
}
inline double TaxRecord::tax_paid() const {
  // @@protoc_insertion_point(field_get:calc.TaxRecord.tax_paid)
  return _internal_tax_paid();
}
inline void TaxRecord::_internal_set_tax_paid(double value) {
  
  _impl_.tax_paid_ = value;
}
inline void TaxRecord::set_tax_paid(double value) {
  _internal_set_tax_paid(value);
  // @@protoc_insertion_point(field_set:calc.TaxRecord.tax_paid)
}

// int32 months_worked = 4;
inline void TaxRecord::clear_months_worked() {
  _impl_.months_worked_ = 0;
}
inline int32_t TaxRecord::_internal_months_worked() const {
  return _impl_.months_worked_;
}
inline int32_t TaxRecord::months_worked() const {
  // @@protoc_insertion_point(field_get:calc.TaxRecord.months_worked)
  return _internal_months_worked();
}
inline void TaxRecord::_internal_set_months_worked(int32_t value) {
  
  _impl_.months_worked_ = value;
}
inline void TaxRecord::set_months_worked(int32_t value) {
  _internal_set_months_worked(value);
  // @@protoc_insertion_point(field_set:calc.TaxRecord.months_worked)
}

// -------------------------------------------------------------------

// PensionRequest

// string customer_id = 1;
inline void PensionRequest::clear_customer_id() {
  _impl_.customer_id_.ClearToEmpty();
}
inline const std::string& PensionRequest::customer_id() const {
  // @@protoc_insertion_point(field_get:calc.PensionRequest.customer_id)
  return _internal_customer_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PensionRequest::set_customer_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.customer_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:calc.PensionRequest.customer_id)
}
inline std::string* PensionRequest::mutable_customer_id() {
  std::string* _s = _internal_mutable_customer_id();
  // @@protoc_insertion_point(field_mutable:calc.PensionRequest.customer_id)
  return _s;
}
inline const std::string& PensionRequest::_internal_customer_id() const {
  return _impl_.customer_id_.Get();
}
inline void PensionRequest::_internal_set_customer_id(const std::string& value) {
  
  _impl_.customer_id_.Set(value, GetArenaForAllocation());
}
inline std::string* PensionRequest::_internal_mutable_customer_id() {
  
  return _impl_.customer_id_.Mutable(GetArenaForAllocation());
}
inline std::string* PensionRequest::release_customer_id() {
  // @@protoc_insertion_point(field_release:calc.PensionRequest.customer_id)
  return _impl_.customer_id_.Release();
}
inline void PensionRequest::set_allocated_customer_id(std::string* customer_id) {
  if (customer_id != nullptr) {
    
  } else {
    
  }
  _impl_.customer_id_.SetAllocated(customer_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.customer_id_.IsDefault()) {
    _impl_.customer_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:calc.PensionRequest.customer_id)
}

// int32 birth_year = 2;
inline void PensionRequest::clear_birth_year() {
  _impl_.birth_year_ = 0;
}
inline int32_t PensionRequest::_internal_birth_year() const {
  return _impl_.birth_year_;
}
inline int32_t PensionRequest::birth_year() const {
  // @@protoc_insertion_point(field_get:calc.PensionRequest.birth_year)
  return _internal_birth_year();
}
inline void PensionRequest::_internal_set_birth_year(int32_t value) {
  
  _impl_.birth_year_ = value;
}
inline void PensionRequest::set_birth_year(int32_t value) {
  _internal_set_birth_year(value);
  // @@protoc_insertion_point(field_set:calc.PensionRequest.birth_year)
}

// int32 target_retirement_year = 3;
inline void PensionRequest::clear_target_retirement_year() {
  _impl_.target_retirement_year_ = 0;
}
inline int32_t PensionRequest::_internal_target_retirement_year() const {
  return _impl_.target_retirement_year_;
}
inline int32_t PensionRequest::target_retirement_year() const {
  // @@protoc_insertion_point(field_get:calc.PensionRequest.target_retirement_year)
  return _internal_target_retirement_year();
}
inline void PensionRequest::_internal_set_target_retirement_year(int32_t value) {
  
  _impl_.target_retirement_year_ = value;
}
inline void PensionRequest::set_target_retirement_year(int32_t value) {
  _internal_set_target_retirement_year(value);
  // @@protoc_insertion_point(field_set:calc.PensionRequest.target_retirement_year)
}

// repeated .calc.TaxRecord history = 4;
inline int PensionRequest::_internal_history_size() const {
  return _impl_.history_.size();
}
inline int PensionRequest::history_size() const {
  return _internal_history_size();
}
inline void PensionRequest::clear_history() {
  _impl_.history_.Clear();
}
inline ::calc::TaxRecord* PensionRequest::mutable_history(int index) {
  // @@protoc_insertion_point(field_mutable:calc.PensionRequest.history)
  return _impl_.history_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::calc::TaxRecord >*
PensionRequest::mutable_history() {
  // @@protoc_insertion_point(field_mutable_list:calc.PensionRequest.history)
  return &_impl_.history_;
}
inline const ::calc::TaxRecord& PensionRequest::_internal_history(int index) const {
  return _impl_.history_.Get(index);
}
inline const ::calc::TaxRecord& PensionRequest::history(int index) const {
  // @@protoc_insertion_point(field_get:calc.PensionRequest.history)
  return _internal_history(index);
}
inline ::calc::TaxRecord* PensionRequest::_internal_add_history() {
  return _impl_.history_.Add();
}
inline ::calc::TaxRecord* PensionRequest::add_history() {
  ::calc::TaxRecord* _add = _internal_add_history();
  // @@protoc_insertion_point(field_add:calc.PensionRequest.history)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::calc::TaxRecord >&
PensionRequest::history() const {
  // @@protoc_insertion_point(field_list:calc.PensionRequest.history)
  return _impl_.history_;
}

// -------------------------------------------------------------------

// PensionResponse

// bool success = 1;
inline void PensionResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool PensionResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool PensionResponse::success() const {
  // @@protoc_insertion_point(field_get:calc.PensionResponse.success)
  return _internal_success();
}
inline void PensionResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void PensionResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:calc.PensionResponse.success)
}

// double estimated_monthly_pension = 2;
inline void PensionResponse::clear_estimated_monthly_pension() {
  _impl_.estimated_monthly_pension_ = 0;
}
inline double PensionResponse::_internal_estimated_monthly_pension() const {
  return _impl_.estimated_monthly_pension_;
}
inline double PensionResponse::estimated_monthly_pension() const {
  // @@protoc_insertion_point(field_get:calc.PensionResponse.estimated_monthly_pension)
  return _internal_estimated_monthly_pension();
}
inline void PensionResponse::_internal_set_estimated_monthly_pension(double value) {
  
  _impl_.estimated_monthly_pension_ = value;
}
inline void PensionResponse::set_estimated_monthly_pension(double value) {
  _internal_set_estimated_monthly_pension(value);
  // @@protoc_insertion_point(field_set:calc.PensionResponse.estimated_monthly_pension)
}

// double total_accumulated_capital = 3;
inline void PensionResponse::clear_total_accumulated_capital() {
  _impl_.total_accumulated_capital_ = 0;
}
inline double PensionResponse::_internal_total_accumulated_capital() const {
  return _impl_.total_accumulated_capital_;
}
inline double PensionResponse::total_accumulated_capital() const {
  // @@protoc_insertion_point(field_get:calc.PensionResponse.total_accumulated_capital)
  return _internal_total_accumulated_capital();
}
inline void PensionResponse::_internal_set_total_accumulated_capital(double value) {
  
  _impl_.total_accumulated_capital_ = value;
}
inline void PensionResponse::set_total_accumulated_capital(double value) {
  _internal_set_total_accumulated_capital(value);
  // @@protoc_insertion_point(field_set:calc.PensionResponse.total_accumulated_capital)
}

// string calculation_breakdown = 4;
inline void PensionResponse::clear_calculation_breakdown() {
  _impl_.calculation_breakdown_.ClearToEmpty();
}
inline const std::string& PensionResponse::calculation_breakdown() const {
  // @@protoc_insertion_point(field_get:calc.PensionResponse.calculation_breakdown)
  return _internal_calculation_breakdown();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PensionResponse::set_calculation_breakdown(ArgT0&& arg0, ArgT... args) {
 
 _impl_.calculation_breakdown_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:calc.PensionResponse.calculation_breakdown)
}
inline std::string* PensionResponse::mutable_calculation_breakdown() {
  std::string* _s = _internal_mutable_calculation_breakdown();
  // @@protoc_insertion_point(field_mutable:calc.PensionResponse.calculation_breakdown)
  return _s;
}
inline const std::string& PensionResponse::_internal_calculation_breakdown() const {
  return _impl_.calculation_breakdown_.Get();
}
inline void PensionResponse::_internal_set_calculation_breakdown(const std::string& value) {
  
  _impl_.calculation_breakdown_.Set(value, GetArenaForAllocation());
}
inline std::string* PensionResponse::_internal_mutable_calculation_breakdown() {
  
  return _impl_.calculation_breakdown_.Mutable(GetArenaForAllocation());
}
inline std::string* PensionResponse::release_calculation_breakdown() {
  // @@protoc_insertion_point(field_release:calc.PensionResponse.calculation_breakdown)
  return _impl_.calculation_breakdown_.Release();
}
inline void PensionResponse::set_allocated_calculation_breakdown(std::string* calculation_breakdown) {
  if (calculation_breakdown != nullptr) {
    
  } else {
    
  }
  _impl_.calculation_breakdown_.SetAllocated(calculation_breakdown, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.calculation_breakdown_.IsDefault()) {
    _impl_.calculation_breakdown_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:calc.PensionResponse.calculation_breakdown)
}

// string error_message = 5;
inline void PensionResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& PensionResponse::error_message() const {
  // @@protoc_insertion_point(field_get:calc.PensionResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PensionResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:calc.PensionResponse.error_message)
}
inline std::string* PensionResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:calc.PensionResponse.error_message)
  return _s;
}
inline const std::string& PensionResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void PensionResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* PensionResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* PensionResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:calc.PensionResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void PensionResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:calc.PensionResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace calc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_calc_2eproto
