// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ocr.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ocr_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ocr_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ocr_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ocr_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ocr_2eproto;
namespace ocr {
class OcrRequest;
struct OcrRequestDefaultTypeInternal;
extern OcrRequestDefaultTypeInternal _OcrRequest_default_instance_;
class OcrResponse;
struct OcrResponseDefaultTypeInternal;
extern OcrResponseDefaultTypeInternal _OcrResponse_default_instance_;
class OcrResponse_DataEntry_DoNotUse;
struct OcrResponse_DataEntry_DoNotUseDefaultTypeInternal;
extern OcrResponse_DataEntry_DoNotUseDefaultTypeInternal _OcrResponse_DataEntry_DoNotUse_default_instance_;
}  // namespace ocr
PROTOBUF_NAMESPACE_OPEN
template<> ::ocr::OcrRequest* Arena::CreateMaybeMessage<::ocr::OcrRequest>(Arena*);
template<> ::ocr::OcrResponse* Arena::CreateMaybeMessage<::ocr::OcrResponse>(Arena*);
template<> ::ocr::OcrResponse_DataEntry_DoNotUse* Arena::CreateMaybeMessage<::ocr::OcrResponse_DataEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ocr {

// ===================================================================

class OcrRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr.OcrRequest) */ {
 public:
  inline OcrRequest() : OcrRequest(nullptr) {}
  ~OcrRequest() override;
  explicit PROTOBUF_CONSTEXPR OcrRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OcrRequest(const OcrRequest& from);
  OcrRequest(OcrRequest&& from) noexcept
    : OcrRequest() {
    *this = ::std::move(from);
  }

  inline OcrRequest& operator=(const OcrRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrRequest& operator=(OcrRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OcrRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const OcrRequest* internal_default_instance() {
    return reinterpret_cast<const OcrRequest*>(
               &_OcrRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OcrRequest& a, OcrRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OcrRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OcrRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OcrRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OcrRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OcrRequest& from) {
    OcrRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr.OcrRequest";
  }
  protected:
  explicit OcrRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileContentFieldNumber = 1,
    kFileExtensionFieldNumber = 2,
    kDocumentTypeFieldNumber = 3,
  };
  // bytes file_content = 1;
  void clear_file_content();
  const std::string& file_content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_content();
  PROTOBUF_NODISCARD std::string* release_file_content();
  void set_allocated_file_content(std::string* file_content);
  private:
  const std::string& _internal_file_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_content(const std::string& value);
  std::string* _internal_mutable_file_content();
  public:

  // string file_extension = 2;
  void clear_file_extension();
  const std::string& file_extension() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_extension(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_extension();
  PROTOBUF_NODISCARD std::string* release_file_extension();
  void set_allocated_file_extension(std::string* file_extension);
  private:
  const std::string& _internal_file_extension() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_extension(const std::string& value);
  std::string* _internal_mutable_file_extension();
  public:

  // string document_type = 3;
  void clear_document_type();
  const std::string& document_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_document_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_document_type();
  PROTOBUF_NODISCARD std::string* release_document_type();
  void set_allocated_document_type(std::string* document_type);
  private:
  const std::string& _internal_document_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_document_type(const std::string& value);
  std::string* _internal_mutable_document_type();
  public:

  // @@protoc_insertion_point(class_scope:ocr.OcrRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_content_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_extension_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr document_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ocr_2eproto;
};
// -------------------------------------------------------------------

class OcrResponse_DataEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<OcrResponse_DataEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<OcrResponse_DataEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  OcrResponse_DataEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR OcrResponse_DataEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit OcrResponse_DataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const OcrResponse_DataEntry_DoNotUse& other);
  static const OcrResponse_DataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const OcrResponse_DataEntry_DoNotUse*>(&_OcrResponse_DataEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "ocr.OcrResponse.DataEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "ocr.OcrResponse.DataEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_ocr_2eproto;
};

// -------------------------------------------------------------------

class OcrResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ocr.OcrResponse) */ {
 public:
  inline OcrResponse() : OcrResponse(nullptr) {}
  ~OcrResponse() override;
  explicit PROTOBUF_CONSTEXPR OcrResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OcrResponse(const OcrResponse& from);
  OcrResponse(OcrResponse&& from) noexcept
    : OcrResponse() {
    *this = ::std::move(from);
  }

  inline OcrResponse& operator=(const OcrResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResponse& operator=(OcrResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OcrResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const OcrResponse* internal_default_instance() {
    return reinterpret_cast<const OcrResponse*>(
               &_OcrResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OcrResponse& a, OcrResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(OcrResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OcrResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OcrResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OcrResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OcrResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OcrResponse& from) {
    OcrResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OcrResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ocr.OcrResponse";
  }
  protected:
  explicit OcrResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kRawTextFieldNumber = 2,
    kErrorMessageFieldNumber = 5,
    kSuccessFieldNumber = 1,
    kConfidenceFieldNumber = 4,
  };
  // map<string, string> data = 3;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_data();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_data();

  // string raw_text = 2;
  void clear_raw_text();
  const std::string& raw_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_raw_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_raw_text();
  PROTOBUF_NODISCARD std::string* release_raw_text();
  void set_allocated_raw_text(std::string* raw_text);
  private:
  const std::string& _internal_raw_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_raw_text(const std::string& value);
  std::string* _internal_mutable_raw_text();
  public:

  // string error_message = 5;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // float confidence = 4;
  void clear_confidence();
  float confidence() const;
  void set_confidence(float value);
  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);
  public:

  // @@protoc_insertion_point(class_scope:ocr.OcrResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        OcrResponse_DataEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_text_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    bool success_;
    float confidence_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ocr_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OcrRequest

// bytes file_content = 1;
inline void OcrRequest::clear_file_content() {
  _impl_.file_content_.ClearToEmpty();
}
inline const std::string& OcrRequest::file_content() const {
  // @@protoc_insertion_point(field_get:ocr.OcrRequest.file_content)
  return _internal_file_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OcrRequest::set_file_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_content_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ocr.OcrRequest.file_content)
}
inline std::string* OcrRequest::mutable_file_content() {
  std::string* _s = _internal_mutable_file_content();
  // @@protoc_insertion_point(field_mutable:ocr.OcrRequest.file_content)
  return _s;
}
inline const std::string& OcrRequest::_internal_file_content() const {
  return _impl_.file_content_.Get();
}
inline void OcrRequest::_internal_set_file_content(const std::string& value) {
  
  _impl_.file_content_.Set(value, GetArenaForAllocation());
}
inline std::string* OcrRequest::_internal_mutable_file_content() {
  
  return _impl_.file_content_.Mutable(GetArenaForAllocation());
}
inline std::string* OcrRequest::release_file_content() {
  // @@protoc_insertion_point(field_release:ocr.OcrRequest.file_content)
  return _impl_.file_content_.Release();
}
inline void OcrRequest::set_allocated_file_content(std::string* file_content) {
  if (file_content != nullptr) {
    
  } else {
    
  }
  _impl_.file_content_.SetAllocated(file_content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_content_.IsDefault()) {
    _impl_.file_content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrRequest.file_content)
}

// string file_extension = 2;
inline void OcrRequest::clear_file_extension() {
  _impl_.file_extension_.ClearToEmpty();
}
inline const std::string& OcrRequest::file_extension() const {
  // @@protoc_insertion_point(field_get:ocr.OcrRequest.file_extension)
  return _internal_file_extension();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OcrRequest::set_file_extension(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_extension_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ocr.OcrRequest.file_extension)
}
inline std::string* OcrRequest::mutable_file_extension() {
  std::string* _s = _internal_mutable_file_extension();
  // @@protoc_insertion_point(field_mutable:ocr.OcrRequest.file_extension)
  return _s;
}
inline const std::string& OcrRequest::_internal_file_extension() const {
  return _impl_.file_extension_.Get();
}
inline void OcrRequest::_internal_set_file_extension(const std::string& value) {
  
  _impl_.file_extension_.Set(value, GetArenaForAllocation());
}
inline std::string* OcrRequest::_internal_mutable_file_extension() {
  
  return _impl_.file_extension_.Mutable(GetArenaForAllocation());
}
inline std::string* OcrRequest::release_file_extension() {
  // @@protoc_insertion_point(field_release:ocr.OcrRequest.file_extension)
  return _impl_.file_extension_.Release();
}
inline void OcrRequest::set_allocated_file_extension(std::string* file_extension) {
  if (file_extension != nullptr) {
    
  } else {
    
  }
  _impl_.file_extension_.SetAllocated(file_extension, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_extension_.IsDefault()) {
    _impl_.file_extension_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrRequest.file_extension)
}

// string document_type = 3;
inline void OcrRequest::clear_document_type() {
  _impl_.document_type_.ClearToEmpty();
}
inline const std::string& OcrRequest::document_type() const {
  // @@protoc_insertion_point(field_get:ocr.OcrRequest.document_type)
  return _internal_document_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OcrRequest::set_document_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.document_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ocr.OcrRequest.document_type)
}
inline std::string* OcrRequest::mutable_document_type() {
  std::string* _s = _internal_mutable_document_type();
  // @@protoc_insertion_point(field_mutable:ocr.OcrRequest.document_type)
  return _s;
}
inline const std::string& OcrRequest::_internal_document_type() const {
  return _impl_.document_type_.Get();
}
inline void OcrRequest::_internal_set_document_type(const std::string& value) {
  
  _impl_.document_type_.Set(value, GetArenaForAllocation());
}
inline std::string* OcrRequest::_internal_mutable_document_type() {
  
  return _impl_.document_type_.Mutable(GetArenaForAllocation());
}
inline std::string* OcrRequest::release_document_type() {
  // @@protoc_insertion_point(field_release:ocr.OcrRequest.document_type)
  return _impl_.document_type_.Release();
}
inline void OcrRequest::set_allocated_document_type(std::string* document_type) {
  if (document_type != nullptr) {
    
  } else {
    
  }
  _impl_.document_type_.SetAllocated(document_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.document_type_.IsDefault()) {
    _impl_.document_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrRequest.document_type)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// OcrResponse

// bool success = 1;
inline void OcrResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool OcrResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool OcrResponse::success() const {
  // @@protoc_insertion_point(field_get:ocr.OcrResponse.success)
  return _internal_success();
}
inline void OcrResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void OcrResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:ocr.OcrResponse.success)
}

// string raw_text = 2;
inline void OcrResponse::clear_raw_text() {
  _impl_.raw_text_.ClearToEmpty();
}
inline const std::string& OcrResponse::raw_text() const {
  // @@protoc_insertion_point(field_get:ocr.OcrResponse.raw_text)
  return _internal_raw_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OcrResponse::set_raw_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.raw_text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ocr.OcrResponse.raw_text)
}
inline std::string* OcrResponse::mutable_raw_text() {
  std::string* _s = _internal_mutable_raw_text();
  // @@protoc_insertion_point(field_mutable:ocr.OcrResponse.raw_text)
  return _s;
}
inline const std::string& OcrResponse::_internal_raw_text() const {
  return _impl_.raw_text_.Get();
}
inline void OcrResponse::_internal_set_raw_text(const std::string& value) {
  
  _impl_.raw_text_.Set(value, GetArenaForAllocation());
}
inline std::string* OcrResponse::_internal_mutable_raw_text() {
  
  return _impl_.raw_text_.Mutable(GetArenaForAllocation());
}
inline std::string* OcrResponse::release_raw_text() {
  // @@protoc_insertion_point(field_release:ocr.OcrResponse.raw_text)
  return _impl_.raw_text_.Release();
}
inline void OcrResponse::set_allocated_raw_text(std::string* raw_text) {
  if (raw_text != nullptr) {
    
  } else {
    
  }
  _impl_.raw_text_.SetAllocated(raw_text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.raw_text_.IsDefault()) {
    _impl_.raw_text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrResponse.raw_text)
}

// map<string, string> data = 3;
inline int OcrResponse::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int OcrResponse::data_size() const {
  return _internal_data_size();
}
inline void OcrResponse::clear_data() {
  _impl_.data_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
OcrResponse::_internal_data() const {
  return _impl_.data_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
OcrResponse::data() const {
  // @@protoc_insertion_point(field_map:ocr.OcrResponse.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
OcrResponse::_internal_mutable_data() {
  return _impl_.data_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
OcrResponse::mutable_data() {
  // @@protoc_insertion_point(field_mutable_map:ocr.OcrResponse.data)
  return _internal_mutable_data();
}

// float confidence = 4;
inline void OcrResponse::clear_confidence() {
  _impl_.confidence_ = 0;
}
inline float OcrResponse::_internal_confidence() const {
  return _impl_.confidence_;
}
inline float OcrResponse::confidence() const {
  // @@protoc_insertion_point(field_get:ocr.OcrResponse.confidence)
  return _internal_confidence();
}
inline void OcrResponse::_internal_set_confidence(float value) {
  
  _impl_.confidence_ = value;
}
inline void OcrResponse::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:ocr.OcrResponse.confidence)
}

// string error_message = 5;
inline void OcrResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& OcrResponse::error_message() const {
  // @@protoc_insertion_point(field_get:ocr.OcrResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OcrResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ocr.OcrResponse.error_message)
}
inline std::string* OcrResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:ocr.OcrResponse.error_message)
  return _s;
}
inline const std::string& OcrResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void OcrResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* OcrResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* OcrResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:ocr.OcrResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void OcrResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ocr

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ocr_2eproto
