<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use UnexpectedValueException;

/**
 * Protobuf type <code>calc.BenefitType</code>
 */
class BenefitType
{
    /**
     * Generated from protobuf enum <code>BENEFIT_NONE = 0;</code>
     */
    const BENEFIT_NONE = 0;
    /**
     * УБД (+25% of subsistence minimum for disabled)
     *
     * Generated from protobuf enum <code>COMBAT_VETERAN = 1;</code>
     */
    const COMBAT_VETERAN = 1;
    /**
     * Почесний донор (+10% of general subsistence minimum)
     *
     * Generated from protobuf enum <code>HONORARY_DONOR = 2;</code>
     */
    const HONORARY_DONOR = 2;
    /**
     * Чорнобилець-ліквідатор (+30% of subsistence minimum for disabled)
     *
     * Generated from protobuf enum <code>CHORNOBYL_LIQUIDATOR = 3;</code>
     */
    const CHORNOBYL_LIQUIDATOR = 3;
    /**
     * Догляд за дитиною з інвалідністю (+10% of subsistence minimum for disabled)
     *
     * Generated from protobuf enum <code>DISABLED_CHILD_CARE = 4;</code>
     */
    const DISABLED_CHILD_CARE = 4;

    private static $valueToName = [
        self::BENEFIT_NONE => 'BENEFIT_NONE',
        self::COMBAT_VETERAN => 'COMBAT_VETERAN',
        self::HONORARY_DONOR => 'HONORARY_DONOR',
        self::CHORNOBYL_LIQUIDATOR => 'CHORNOBYL_LIQUIDATOR',
        self::DISABLED_CHILD_CARE => 'DISABLED_CHILD_CARE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

