<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.CalculatePensionResponse</code>
 */
class CalculatePensionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Clamped final pension payment (UAH)
     *
     * Generated from protobuf field <code>double final_pension = 2;</code>
     */
    protected $final_pension = 0.0;
    /**
     * P = Zp * Kz * Ks
     *
     * Generated from protobuf field <code>double base_pension = 3;</code>
     */
    protected $base_pension = 0.0;
    /**
     * Zp
     *
     * Generated from protobuf field <code>double zp_macroeconomic_average = 4;</code>
     */
    protected $zp_macroeconomic_average = 0.0;
    /**
     * Kz
     *
     * Generated from protobuf field <code>double kz_wage_coefficient = 5;</code>
     */
    protected $kz_wage_coefficient = 0.0;
    /**
     * Ks
     *
     * Generated from protobuf field <code>double ks_service_coefficient = 6;</code>
     */
    protected $ks_service_coefficient = 0.0;
    /**
     * Generated from protobuf field <code>int32 total_service_months = 7;</code>
     */
    protected $total_service_months = 0;
    /**
     * e.g. 1.0, 0.9, 0.5
     *
     * Generated from protobuf field <code>double pension_type_modifier = 8;</code>
     */
    protected $pension_type_modifier = 0.0;
    /**
     * Surcharge for years over 30 (women) or 35 (men)
     *
     * Generated from protobuf field <code>double extra_service_allowance = 9;</code>
     */
    protected $extra_service_allowance = 0.0;
    /**
     * Sum of all active benefits
     *
     * Generated from protobuf field <code>double total_benefit_surcharges = 10;</code>
     */
    protected $total_benefit_surcharges = 0.0;
    /**
     * Unclamped sum
     *
     * Generated from protobuf field <code>double pre_clamped_pension = 11;</code>
     */
    protected $pre_clamped_pension = 0.0;
    /**
     * Generated from protobuf field <code>bool is_minimum_clamped = 12;</code>
     */
    protected $is_minimum_clamped = false;
    /**
     * Generated from protobuf field <code>bool is_maximum_clamped = 13;</code>
     */
    protected $is_maximum_clamped = false;
    /**
     * Generated from protobuf field <code>repeated .calc.BenefitSurchargeDetail applied_benefits = 14;</code>
     */
    private $applied_benefits;
    /**
     * Generated from protobuf field <code>repeated string calculation_logs = 15;</code>
     */
    private $calculation_logs;
    /**
     * Generated from protobuf field <code>string error_message = 16;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type float $final_pension
     *           Clamped final pension payment (UAH)
     *     @type float $base_pension
     *           P = Zp * Kz * Ks
     *     @type float $zp_macroeconomic_average
     *           Zp
     *     @type float $kz_wage_coefficient
     *           Kz
     *     @type float $ks_service_coefficient
     *           Ks
     *     @type int $total_service_months
     *     @type float $pension_type_modifier
     *           e.g. 1.0, 0.9, 0.5
     *     @type float $extra_service_allowance
     *           Surcharge for years over 30 (women) or 35 (men)
     *     @type float $total_benefit_surcharges
     *           Sum of all active benefits
     *     @type float $pre_clamped_pension
     *           Unclamped sum
     *     @type bool $is_minimum_clamped
     *     @type bool $is_maximum_clamped
     *     @type array<\Calc\BenefitSurchargeDetail>|\Google\Protobuf\Internal\RepeatedField $applied_benefits
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $calculation_logs
     *     @type string $error_message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Clamped final pension payment (UAH)
     *
     * Generated from protobuf field <code>double final_pension = 2;</code>
     * @return float
     */
    public function getFinalPension()
    {
        return $this->final_pension;
    }

    /**
     * Clamped final pension payment (UAH)
     *
     * Generated from protobuf field <code>double final_pension = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFinalPension($var)
    {
        GPBUtil::checkDouble($var);
        $this->final_pension = $var;

        return $this;
    }

    /**
     * P = Zp * Kz * Ks
     *
     * Generated from protobuf field <code>double base_pension = 3;</code>
     * @return float
     */
    public function getBasePension()
    {
        return $this->base_pension;
    }

    /**
     * P = Zp * Kz * Ks
     *
     * Generated from protobuf field <code>double base_pension = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setBasePension($var)
    {
        GPBUtil::checkDouble($var);
        $this->base_pension = $var;

        return $this;
    }

    /**
     * Zp
     *
     * Generated from protobuf field <code>double zp_macroeconomic_average = 4;</code>
     * @return float
     */
    public function getZpMacroeconomicAverage()
    {
        return $this->zp_macroeconomic_average;
    }

    /**
     * Zp
     *
     * Generated from protobuf field <code>double zp_macroeconomic_average = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setZpMacroeconomicAverage($var)
    {
        GPBUtil::checkDouble($var);
        $this->zp_macroeconomic_average = $var;

        return $this;
    }

    /**
     * Kz
     *
     * Generated from protobuf field <code>double kz_wage_coefficient = 5;</code>
     * @return float
     */
    public function getKzWageCoefficient()
    {
        return $this->kz_wage_coefficient;
    }

    /**
     * Kz
     *
     * Generated from protobuf field <code>double kz_wage_coefficient = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setKzWageCoefficient($var)
    {
        GPBUtil::checkDouble($var);
        $this->kz_wage_coefficient = $var;

        return $this;
    }

    /**
     * Ks
     *
     * Generated from protobuf field <code>double ks_service_coefficient = 6;</code>
     * @return float
     */
    public function getKsServiceCoefficient()
    {
        return $this->ks_service_coefficient;
    }

    /**
     * Ks
     *
     * Generated from protobuf field <code>double ks_service_coefficient = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setKsServiceCoefficient($var)
    {
        GPBUtil::checkDouble($var);
        $this->ks_service_coefficient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_service_months = 7;</code>
     * @return int
     */
    public function getTotalServiceMonths()
    {
        return $this->total_service_months;
    }

    /**
     * Generated from protobuf field <code>int32 total_service_months = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalServiceMonths($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_service_months = $var;

        return $this;
    }

    /**
     * e.g. 1.0, 0.9, 0.5
     *
     * Generated from protobuf field <code>double pension_type_modifier = 8;</code>
     * @return float
     */
    public function getPensionTypeModifier()
    {
        return $this->pension_type_modifier;
    }

    /**
     * e.g. 1.0, 0.9, 0.5
     *
     * Generated from protobuf field <code>double pension_type_modifier = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setPensionTypeModifier($var)
    {
        GPBUtil::checkDouble($var);
        $this->pension_type_modifier = $var;

        return $this;
    }

    /**
     * Surcharge for years over 30 (women) or 35 (men)
     *
     * Generated from protobuf field <code>double extra_service_allowance = 9;</code>
     * @return float
     */
    public function getExtraServiceAllowance()
    {
        return $this->extra_service_allowance;
    }

    /**
     * Surcharge for years over 30 (women) or 35 (men)
     *
     * Generated from protobuf field <code>double extra_service_allowance = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setExtraServiceAllowance($var)
    {
        GPBUtil::checkDouble($var);
        $this->extra_service_allowance = $var;

        return $this;
    }

    /**
     * Sum of all active benefits
     *
     * Generated from protobuf field <code>double total_benefit_surcharges = 10;</code>
     * @return float
     */
    public function getTotalBenefitSurcharges()
    {
        return $this->total_benefit_surcharges;
    }

    /**
     * Sum of all active benefits
     *
     * Generated from protobuf field <code>double total_benefit_surcharges = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalBenefitSurcharges($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_benefit_surcharges = $var;

        return $this;
    }

    /**
     * Unclamped sum
     *
     * Generated from protobuf field <code>double pre_clamped_pension = 11;</code>
     * @return float
     */
    public function getPreClampedPension()
    {
        return $this->pre_clamped_pension;
    }

    /**
     * Unclamped sum
     *
     * Generated from protobuf field <code>double pre_clamped_pension = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setPreClampedPension($var)
    {
        GPBUtil::checkDouble($var);
        $this->pre_clamped_pension = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_minimum_clamped = 12;</code>
     * @return bool
     */
    public function getIsMinimumClamped()
    {
        return $this->is_minimum_clamped;
    }

    /**
     * Generated from protobuf field <code>bool is_minimum_clamped = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMinimumClamped($var)
    {
        GPBUtil::checkBool($var);
        $this->is_minimum_clamped = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_maximum_clamped = 13;</code>
     * @return bool
     */
    public function getIsMaximumClamped()
    {
        return $this->is_maximum_clamped;
    }

    /**
     * Generated from protobuf field <code>bool is_maximum_clamped = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMaximumClamped($var)
    {
        GPBUtil::checkBool($var);
        $this->is_maximum_clamped = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.BenefitSurchargeDetail applied_benefits = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAppliedBenefits()
    {
        return $this->applied_benefits;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.BenefitSurchargeDetail applied_benefits = 14;</code>
     * @param array<\Calc\BenefitSurchargeDetail>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAppliedBenefits($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Calc\BenefitSurchargeDetail::class);
        $this->applied_benefits = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string calculation_logs = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCalculationLogs()
    {
        return $this->calculation_logs;
    }

    /**
     * Generated from protobuf field <code>repeated string calculation_logs = 15;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCalculationLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->calculation_logs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 16;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

