<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.CalculatePensionRequest</code>
 */
class CalculatePensionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customer_id = 1;</code>
     */
    protected $customer_id = '';
    /**
     * Generated from protobuf field <code>.calc.Gender gender = 2;</code>
     */
    protected $gender = 0;
    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string date_of_birth = 3;</code>
     */
    protected $date_of_birth = '';
    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string retirement_date = 4;</code>
     */
    protected $retirement_date = '';
    /**
     * Generated from protobuf field <code>.calc.PensionType pension_type = 5;</code>
     */
    protected $pension_type = 0;
    /**
     * Generated from protobuf field <code>.calc.DisabilityGroup disability_group = 6;</code>
     */
    protected $disability_group = 0;
    /**
     * For LOSS_OF_BREADWINNER
     *
     * Generated from protobuf field <code>int32 dependents_count = 7;</code>
     */
    protected $dependents_count = 0;
    /**
     * Generated from protobuf field <code>repeated .calc.EmploymentPeriod employment_history = 8;</code>
     */
    private $employment_history;
    /**
     * Generated from protobuf field <code>repeated .calc.SalaryMonthRecord salary_history = 9;</code>
     */
    private $salary_history;
    /**
     * Generated from protobuf field <code>repeated .calc.BenefitType benefits = 10;</code>
     */
    private $benefits;
    /**
     * Generated from protobuf field <code>.calc.SubsistenceMinimums subsistence_minimums = 11;</code>
     */
    protected $subsistence_minimums = null;
    /**
     * Drop worst 10% of salary months if it improves Kz
     *
     * Generated from protobuf field <code>bool enable_optimization_rule = 12;</code>
     */
    protected $enable_optimization_rule = false;
    /**
     * Average national salary for 3 prior years (Zp)
     *
     * Generated from protobuf field <code>double zp_macroeconomic_average = 13;</code>
     */
    protected $zp_macroeconomic_average = 0.0;
    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>repeated .calc.TaxRecord history = 14;</code>
     */
    private $history;
    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>int32 birth_year = 15;</code>
     */
    protected $birth_year = 0;
    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>int32 target_retirement_year = 16;</code>
     */
    protected $target_retirement_year = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customer_id
     *     @type int $gender
     *     @type string $date_of_birth
     *           "YYYY-MM-DD"
     *     @type string $retirement_date
     *           "YYYY-MM-DD"
     *     @type int $pension_type
     *     @type int $disability_group
     *     @type int $dependents_count
     *           For LOSS_OF_BREADWINNER
     *     @type array<\Calc\EmploymentPeriod>|\Google\Protobuf\Internal\RepeatedField $employment_history
     *     @type array<\Calc\SalaryMonthRecord>|\Google\Protobuf\Internal\RepeatedField $salary_history
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $benefits
     *     @type \Calc\SubsistenceMinimums $subsistence_minimums
     *     @type bool $enable_optimization_rule
     *           Drop worst 10% of salary months if it improves Kz
     *     @type float $zp_macroeconomic_average
     *           Average national salary for 3 prior years (Zp)
     *     @type array<\Calc\TaxRecord>|\Google\Protobuf\Internal\RepeatedField $history
     *           Backward compatibility
     *     @type int $birth_year
     *           Backward compatibility
     *     @type int $target_retirement_year
     *           Backward compatibility
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customer_id = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }

    /**
     * Generated from protobuf field <code>string customer_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.calc.Gender gender = 2;</code>
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>.calc.Gender gender = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, \Calc\Gender::class);
        $this->gender = $var;

        return $this;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string date_of_birth = 3;</code>
     * @return string
     */
    public function getDateOfBirth()
    {
        return $this->date_of_birth;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string date_of_birth = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDateOfBirth($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_of_birth = $var;

        return $this;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string retirement_date = 4;</code>
     * @return string
     */
    public function getRetirementDate()
    {
        return $this->retirement_date;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string retirement_date = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRetirementDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->retirement_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.calc.PensionType pension_type = 5;</code>
     * @return int
     */
    public function getPensionType()
    {
        return $this->pension_type;
    }

    /**
     * Generated from protobuf field <code>.calc.PensionType pension_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPensionType($var)
    {
        GPBUtil::checkEnum($var, \Calc\PensionType::class);
        $this->pension_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.calc.DisabilityGroup disability_group = 6;</code>
     * @return int
     */
    public function getDisabilityGroup()
    {
        return $this->disability_group;
    }

    /**
     * Generated from protobuf field <code>.calc.DisabilityGroup disability_group = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDisabilityGroup($var)
    {
        GPBUtil::checkEnum($var, \Calc\DisabilityGroup::class);
        $this->disability_group = $var;

        return $this;
    }

    /**
     * For LOSS_OF_BREADWINNER
     *
     * Generated from protobuf field <code>int32 dependents_count = 7;</code>
     * @return int
     */
    public function getDependentsCount()
    {
        return $this->dependents_count;
    }

    /**
     * For LOSS_OF_BREADWINNER
     *
     * Generated from protobuf field <code>int32 dependents_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDependentsCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->dependents_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.EmploymentPeriod employment_history = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmploymentHistory()
    {
        return $this->employment_history;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.EmploymentPeriod employment_history = 8;</code>
     * @param array<\Calc\EmploymentPeriod>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmploymentHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Calc\EmploymentPeriod::class);
        $this->employment_history = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.SalaryMonthRecord salary_history = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSalaryHistory()
    {
        return $this->salary_history;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.SalaryMonthRecord salary_history = 9;</code>
     * @param array<\Calc\SalaryMonthRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSalaryHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Calc\SalaryMonthRecord::class);
        $this->salary_history = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.BenefitType benefits = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBenefits()
    {
        return $this->benefits;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.BenefitType benefits = 10;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBenefits($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Calc\BenefitType::class);
        $this->benefits = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.calc.SubsistenceMinimums subsistence_minimums = 11;</code>
     * @return \Calc\SubsistenceMinimums|null
     */
    public function getSubsistenceMinimums()
    {
        return $this->subsistence_minimums;
    }

    public function hasSubsistenceMinimums()
    {
        return isset($this->subsistence_minimums);
    }

    public function clearSubsistenceMinimums()
    {
        unset($this->subsistence_minimums);
    }

    /**
     * Generated from protobuf field <code>.calc.SubsistenceMinimums subsistence_minimums = 11;</code>
     * @param \Calc\SubsistenceMinimums $var
     * @return $this
     */
    public function setSubsistenceMinimums($var)
    {
        GPBUtil::checkMessage($var, \Calc\SubsistenceMinimums::class);
        $this->subsistence_minimums = $var;

        return $this;
    }

    /**
     * Drop worst 10% of salary months if it improves Kz
     *
     * Generated from protobuf field <code>bool enable_optimization_rule = 12;</code>
     * @return bool
     */
    public function getEnableOptimizationRule()
    {
        return $this->enable_optimization_rule;
    }

    /**
     * Drop worst 10% of salary months if it improves Kz
     *
     * Generated from protobuf field <code>bool enable_optimization_rule = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableOptimizationRule($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_optimization_rule = $var;

        return $this;
    }

    /**
     * Average national salary for 3 prior years (Zp)
     *
     * Generated from protobuf field <code>double zp_macroeconomic_average = 13;</code>
     * @return float
     */
    public function getZpMacroeconomicAverage()
    {
        return $this->zp_macroeconomic_average;
    }

    /**
     * Average national salary for 3 prior years (Zp)
     *
     * Generated from protobuf field <code>double zp_macroeconomic_average = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setZpMacroeconomicAverage($var)
    {
        GPBUtil::checkDouble($var);
        $this->zp_macroeconomic_average = $var;

        return $this;
    }

    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>repeated .calc.TaxRecord history = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHistory()
    {
        return $this->history;
    }

    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>repeated .calc.TaxRecord history = 14;</code>
     * @param array<\Calc\TaxRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Calc\TaxRecord::class);
        $this->history = $arr;

        return $this;
    }

    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>int32 birth_year = 15;</code>
     * @return int
     */
    public function getBirthYear()
    {
        return $this->birth_year;
    }

    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>int32 birth_year = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setBirthYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->birth_year = $var;

        return $this;
    }

    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>int32 target_retirement_year = 16;</code>
     * @return int
     */
    public function getTargetRetirementYear()
    {
        return $this->target_retirement_year;
    }

    /**
     * Backward compatibility
     *
     * Generated from protobuf field <code>int32 target_retirement_year = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setTargetRetirementYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->target_retirement_year = $var;

        return $this;
    }

}

