<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use UnexpectedValueException;

/**
 * Protobuf type <code>calc.DisabilityGroup</code>
 */
class DisabilityGroup
{
    /**
     * Generated from protobuf enum <code>DISABILITY_NONE = 0;</code>
     */
    const DISABILITY_NONE = 0;
    /**
     * Generated from protobuf enum <code>GROUP_1 = 1;</code>
     */
    const GROUP_1 = 1;
    /**
     * Generated from protobuf enum <code>GROUP_2 = 2;</code>
     */
    const GROUP_2 = 2;
    /**
     * Generated from protobuf enum <code>GROUP_3 = 3;</code>
     */
    const GROUP_3 = 3;

    private static $valueToName = [
        self::DISABILITY_NONE => 'DISABILITY_NONE',
        self::GROUP_1 => 'GROUP_1',
        self::GROUP_2 => 'GROUP_2',
        self::GROUP_3 => 'GROUP_3',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

