<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.EmploymentPeriod</code>
 */
class EmploymentPeriod extends \Google\Protobuf\Internal\Message
{
    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string start_date = 1;</code>
     */
    protected $start_date = '';
    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string end_date = 2;</code>
     */
    protected $end_date = '';
    /**
     * e.g. 1.0 (standard) or 2.0 (hazardous/dangerous work)
     *
     * Generated from protobuf field <code>double multiplier = 3;</code>
     */
    protected $multiplier = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $start_date
     *           "YYYY-MM-DD"
     *     @type string $end_date
     *           "YYYY-MM-DD"
     *     @type float $multiplier
     *           e.g. 1.0 (standard) or 2.0 (hazardous/dangerous work)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string start_date = 1;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string start_date = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string end_date = 2;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * "YYYY-MM-DD"
     *
     * Generated from protobuf field <code>string end_date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

    /**
     * e.g. 1.0 (standard) or 2.0 (hazardous/dangerous work)
     *
     * Generated from protobuf field <code>double multiplier = 3;</code>
     * @return float
     */
    public function getMultiplier()
    {
        return $this->multiplier;
    }

    /**
     * e.g. 1.0 (standard) or 2.0 (hazardous/dangerous work)
     *
     * Generated from protobuf field <code>double multiplier = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMultiplier($var)
    {
        GPBUtil::checkDouble($var);
        $this->multiplier = $var;

        return $this;
    }

}

