<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Calc;

/**
 * Generated from protobuf message <code>calc.GetAverageSalariesRequest</code>
 */
class GetAverageSalariesRequest extends Message
{
    /**
     * Generated from protobuf field <code>repeated int32 years = 1;</code>
     */
    private $years;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type array<int>|\Google\Protobuf\Internal\RepeatedField $years
     *                                                          }
     */
    public function __construct($data = null)
    {
        Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int32 years = 1;</code>
     *
     * @return RepeatedField
     */
    public function getYears()
    {
        return $this->years;
    }

    /**
     * Generated from protobuf field <code>repeated int32 years = 1;</code>
     *
     * @param  array<int>|RepeatedField  $var
     * @return $this
     */
    public function setYears($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::INT32);
        $this->years = $arr;

        return $this;
    }
}
