<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Calc;

/**
 * Generated from protobuf message <code>calc.ListCoefficientsResponse</code>
 */
class ListCoefficientsResponse extends Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;

    /**
     * Generated from protobuf field <code>repeated .calc.PensionCoefficient coefficients = 2;</code>
     */
    private $coefficients;

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type bool $success
     * @type array<\Calc\PensionCoefficient>|\Google\Protobuf\Internal\RepeatedField $coefficients
     * @type string $error_message
     *              }
     */
    public function __construct($data = null)
    {
        Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     *
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     *
     * @param  bool  $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.PensionCoefficient coefficients = 2;</code>
     *
     * @return RepeatedField
     */
    public function getCoefficients()
    {
        return $this->coefficients;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.PensionCoefficient coefficients = 2;</code>
     *
     * @param  array<PensionCoefficient>|RepeatedField  $var
     * @return $this
     */
    public function setCoefficients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, PensionCoefficient::class);
        $this->coefficients = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     *
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     *
     * @param  string  $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, true);
        $this->error_message = $var;

        return $this;
    }
}
