<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\Message;
use GPBMetadata\Calc;

/**
 * Generated from protobuf message <code>calc.ListCoefficientsRequest</code>
 */
class ListCoefficientsRequest extends Message
{
    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = null)
    {
        Calc::initOnce();
        parent::__construct($data);
    }
}
