<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.PensionRequest</code>
 */
class PensionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string customer_id = 1;</code>
     */
    protected $customer_id = '';
    /**
     * Generated from protobuf field <code>int32 birth_year = 2;</code>
     */
    protected $birth_year = 0;
    /**
     * Generated from protobuf field <code>int32 target_retirement_year = 3;</code>
     */
    protected $target_retirement_year = 0;
    /**
     * Generated from protobuf field <code>repeated .calc.TaxRecord history = 4;</code>
     */
    private $history;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customer_id
     *     @type int $birth_year
     *     @type int $target_retirement_year
     *     @type array<\Calc\TaxRecord>|\Google\Protobuf\Internal\RepeatedField $history
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string customer_id = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }

    /**
     * Generated from protobuf field <code>string customer_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 birth_year = 2;</code>
     * @return int
     */
    public function getBirthYear()
    {
        return $this->birth_year;
    }

    /**
     * Generated from protobuf field <code>int32 birth_year = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBirthYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->birth_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 target_retirement_year = 3;</code>
     * @return int
     */
    public function getTargetRetirementYear()
    {
        return $this->target_retirement_year;
    }

    /**
     * Generated from protobuf field <code>int32 target_retirement_year = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTargetRetirementYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->target_retirement_year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.TaxRecord history = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHistory()
    {
        return $this->history;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.TaxRecord history = 4;</code>
     * @param array<\Calc\TaxRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHistory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Calc\TaxRecord::class);
        $this->history = $arr;

        return $this;
    }

}

