<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use UnexpectedValueException;

/**
 * Protobuf type <code>calc.PensionType</code>
 */
class PensionType
{
    /**
     * Generated from protobuf enum <code>OLD_AGE = 0;</code>
     */
    const OLD_AGE = 0;
    /**
     * Generated from protobuf enum <code>DISABILITY = 1;</code>
     */
    const DISABILITY = 1;
    /**
     * Generated from protobuf enum <code>LOSS_OF_BREADWINNER = 2;</code>
     */
    const LOSS_OF_BREADWINNER = 2;

    private static $valueToName = [
        self::OLD_AGE => 'OLD_AGE',
        self::DISABILITY => 'DISABILITY',
        self::LOSS_OF_BREADWINNER => 'LOSS_OF_BREADWINNER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

