<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.PensionResponse</code>
 */
class PensionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>double estimated_monthly_pension = 2;</code>
     */
    protected $estimated_monthly_pension = 0.0;
    /**
     * Generated from protobuf field <code>double total_accumulated_capital = 3;</code>
     */
    protected $total_accumulated_capital = 0.0;
    /**
     * Generated from protobuf field <code>string calculation_breakdown = 4;</code>
     */
    protected $calculation_breakdown = '';
    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type float $estimated_monthly_pension
     *     @type float $total_accumulated_capital
     *     @type string $calculation_breakdown
     *     @type string $error_message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double estimated_monthly_pension = 2;</code>
     * @return float
     */
    public function getEstimatedMonthlyPension()
    {
        return $this->estimated_monthly_pension;
    }

    /**
     * Generated from protobuf field <code>double estimated_monthly_pension = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setEstimatedMonthlyPension($var)
    {
        GPBUtil::checkDouble($var);
        $this->estimated_monthly_pension = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_accumulated_capital = 3;</code>
     * @return float
     */
    public function getTotalAccumulatedCapital()
    {
        return $this->total_accumulated_capital;
    }

    /**
     * Generated from protobuf field <code>double total_accumulated_capital = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalAccumulatedCapital($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_accumulated_capital = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string calculation_breakdown = 4;</code>
     * @return string
     */
    public function getCalculationBreakdown()
    {
        return $this->calculation_breakdown;
    }

    /**
     * Generated from protobuf field <code>string calculation_breakdown = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCalculationBreakdown($var)
    {
        GPBUtil::checkString($var, True);
        $this->calculation_breakdown = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

