<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.SalaryMonthRecord</code>
 */
class SalaryMonthRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>int32 month = 2;</code>
     */
    protected $month = 0;
    /**
     * Generated from protobuf field <code>double amount = 3;</code>
     */
    protected $amount = 0.0;
    /**
     * Conscription, study, child care < 3 yrs, martial law, quarantine
     *
     * Generated from protobuf field <code>bool is_special_period = 4;</code>
     */
    protected $is_special_period = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $year
     *     @type int $month
     *     @type float $amount
     *     @type bool $is_special_period
     *           Conscription, study, child care < 3 yrs, martial law, quarantine
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 month = 2;</code>
     * @return int
     */
    public function getMonth()
    {
        return $this->month;
    }

    /**
     * Generated from protobuf field <code>int32 month = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMonth($var)
    {
        GPBUtil::checkInt32($var);
        $this->month = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 3;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Conscription, study, child care < 3 yrs, martial law, quarantine
     *
     * Generated from protobuf field <code>bool is_special_period = 4;</code>
     * @return bool
     */
    public function getIsSpecialPeriod()
    {
        return $this->is_special_period;
    }

    /**
     * Conscription, study, child care < 3 yrs, martial law, quarantine
     *
     * Generated from protobuf field <code>bool is_special_period = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSpecialPeriod($var)
    {
        GPBUtil::checkBool($var);
        $this->is_special_period = $var;

        return $this;
    }

}

