<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.SubsistenceMinimumRecord</code>
 */
class SubsistenceMinimumRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>double for_disabled_persons = 3;</code>
     */
    protected $for_disabled_persons = 0.0;
    /**
     * Generated from protobuf field <code>double general_minimum = 4;</code>
     */
    protected $general_minimum = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $year
     *     @type float $for_disabled_persons
     *     @type float $general_minimum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double for_disabled_persons = 3;</code>
     * @return float
     */
    public function getForDisabledPersons()
    {
        return $this->for_disabled_persons;
    }

    /**
     * Generated from protobuf field <code>double for_disabled_persons = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setForDisabledPersons($var)
    {
        GPBUtil::checkDouble($var);
        $this->for_disabled_persons = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double general_minimum = 4;</code>
     * @return float
     */
    public function getGeneralMinimum()
    {
        return $this->general_minimum;
    }

    /**
     * Generated from protobuf field <code>double general_minimum = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setGeneralMinimum($var)
    {
        GPBUtil::checkDouble($var);
        $this->general_minimum = $var;

        return $this;
    }

}

