<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.SubsistenceMinimums</code>
 */
class SubsistenceMinimums extends \Google\Protobuf\Internal\Message
{
    /**
     * e.g. 2361.0 UAH
     *
     * Generated from protobuf field <code>double for_disabled_persons = 1;</code>
     */
    protected $for_disabled_persons = 0.0;
    /**
     * e.g. 2920.0 UAH
     *
     * Generated from protobuf field <code>double general_minimum = 2;</code>
     */
    protected $general_minimum = 0.0;
    /**
     * e.g. 10340.35 UAH
     *
     * Generated from protobuf field <code>double age_surcharge_cap = 3;</code>
     */
    protected $age_surcharge_cap = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $for_disabled_persons
     *           e.g. 2361.0 UAH
     *     @type float $general_minimum
     *           e.g. 2920.0 UAH
     *     @type float $age_surcharge_cap
     *           e.g. 10340.35 UAH
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * e.g. 2361.0 UAH
     *
     * Generated from protobuf field <code>double for_disabled_persons = 1;</code>
     * @return float
     */
    public function getForDisabledPersons()
    {
        return $this->for_disabled_persons;
    }

    /**
     * e.g. 2361.0 UAH
     *
     * Generated from protobuf field <code>double for_disabled_persons = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setForDisabledPersons($var)
    {
        GPBUtil::checkDouble($var);
        $this->for_disabled_persons = $var;

        return $this;
    }

    /**
     * e.g. 2920.0 UAH
     *
     * Generated from protobuf field <code>double general_minimum = 2;</code>
     * @return float
     */
    public function getGeneralMinimum()
    {
        return $this->general_minimum;
    }

    /**
     * e.g. 2920.0 UAH
     *
     * Generated from protobuf field <code>double general_minimum = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setGeneralMinimum($var)
    {
        GPBUtil::checkDouble($var);
        $this->general_minimum = $var;

        return $this;
    }

    /**
     * e.g. 10340.35 UAH
     *
     * Generated from protobuf field <code>double age_surcharge_cap = 3;</code>
     * @return float
     */
    public function getAgeSurchargeCap()
    {
        return $this->age_surcharge_cap;
    }

    /**
     * e.g. 10340.35 UAH
     *
     * Generated from protobuf field <code>double age_surcharge_cap = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAgeSurchargeCap($var)
    {
        GPBUtil::checkDouble($var);
        $this->age_surcharge_cap = $var;

        return $this;
    }

}

