<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use GPBMetadata\Calc;

/**
 * Generated from protobuf message <code>calc.SyncAverageSalariesRequest</code>
 */
class SyncAverageSalariesRequest extends Message
{
    /**
     * Generated from protobuf field <code>repeated .calc.AverageSalaryRecord salaries = 1;</code>
     */
    private $salaries;

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type array<\Calc\AverageSalaryRecord>|\Google\Protobuf\Internal\RepeatedField $salaries
     *                                                                                }
     */
    public function __construct($data = null)
    {
        Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .calc.AverageSalaryRecord salaries = 1;</code>
     *
     * @return RepeatedField
     */
    public function getSalaries()
    {
        return $this->salaries;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.AverageSalaryRecord salaries = 1;</code>
     *
     * @param  array<AverageSalaryRecord>|RepeatedField  $var
     * @return $this
     */
    public function setSalaries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, AverageSalaryRecord::class);
        $this->salaries = $arr;

        return $this;
    }
}
