<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.SyncAverageSalariesRequest</code>
 */
class SyncAverageSalariesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .calc.AverageSalaryRecord salaries = 1;</code>
     */
    private $salaries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Calc\AverageSalaryRecord>|\Google\Protobuf\Internal\RepeatedField $salaries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .calc.AverageSalaryRecord salaries = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSalaries()
    {
        return $this->salaries;
    }

    /**
     * Generated from protobuf field <code>repeated .calc.AverageSalaryRecord salaries = 1;</code>
     * @param array<\Calc\AverageSalaryRecord>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSalaries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Calc\AverageSalaryRecord::class);
        $this->salaries = $arr;

        return $this;
    }

}

