<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.TaxRecord</code>
 */
class TaxRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     */
    protected $year = 0;
    /**
     * Generated from protobuf field <code>double annual_income = 2;</code>
     */
    protected $annual_income = 0.0;
    /**
     * Generated from protobuf field <code>double tax_paid = 3;</code>
     */
    protected $tax_paid = 0.0;
    /**
     * Generated from protobuf field <code>int32 months_worked = 4;</code>
     */
    protected $months_worked = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $year
     *     @type float $annual_income
     *     @type float $tax_paid
     *     @type int $months_worked
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double annual_income = 2;</code>
     * @return float
     */
    public function getAnnualIncome()
    {
        return $this->annual_income;
    }

    /**
     * Generated from protobuf field <code>double annual_income = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAnnualIncome($var)
    {
        GPBUtil::checkDouble($var);
        $this->annual_income = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tax_paid = 3;</code>
     * @return float
     */
    public function getTaxPaid()
    {
        return $this->tax_paid;
    }

    /**
     * Generated from protobuf field <code>double tax_paid = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTaxPaid($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax_paid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 months_worked = 4;</code>
     * @return int
     */
    public function getMonthsWorked()
    {
        return $this->months_worked;
    }

    /**
     * Generated from protobuf field <code>int32 months_worked = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMonthsWorked($var)
    {
        GPBUtil::checkInt32($var);
        $this->months_worked = $var;

        return $this;
    }

}

