<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

namespace Calc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calc.UpdateCoefficientResponse</code>
 */
class UpdateCoefficientResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Generated from protobuf field <code>.calc.PensionCoefficient coefficient = 2;</code>
     */
    protected $coefficient = null;
    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type \Calc\PensionCoefficient $coefficient
     *     @type string $error_message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.calc.PensionCoefficient coefficient = 2;</code>
     * @return \Calc\PensionCoefficient|null
     */
    public function getCoefficient()
    {
        return $this->coefficient;
    }

    public function hasCoefficient()
    {
        return isset($this->coefficient);
    }

    public function clearCoefficient()
    {
        unset($this->coefficient);
    }

    /**
     * Generated from protobuf field <code>.calc.PensionCoefficient coefficient = 2;</code>
     * @param \Calc\PensionCoefficient $var
     * @return $this
     */
    public function setCoefficient($var)
    {
        GPBUtil::checkMessage($var, \Calc\PensionCoefficient::class);
        $this->coefficient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

