name: Calc CI

on:
  push:
    paths:
      - 'calc/**'
  pull_request:
    paths:
      - 'calc/**'

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./calc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (GTest)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake g++

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: cd build && ctest --output-on-failure