name: OCR CI (Bypass)

on:
  pull_request:
    paths-ignore:
      - 'ocr/**'
      - 'protos/ocr.proto'

permissions:
  contents: read

jobs:
  ocr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI
        run: echo "No changes in ocr/ and protos/ocr.proto. Skipping OCR CI to unblock the PR."